# vs2019 required for CUDA NVCC compatibility on Windows
c_compiler:                        # [win]
  - vs2019                         # [win]
cxx_compiler:                      # [win]
  - vs2019                         # [win]

mkl:
  - '2025'                         # [win or (linux and x86_64)]

openblas:
  - 0                              # [linux]

blas_impl:
  - mkl                        # [win or (linux and x86_64)]
  - openblas                   # [linux]
  - accelerate                 # [osx]
  - cublas                     # [win or linux]

gpu_variant:
  - none
  - cuda-12                    # [win or linux]
  - cuda-13                    # [win or linux]
  - cuda-13                    # [win or linux]

cuda_compiler:                 # [win or linux]
  - cuda-nvcc                  # [win or linux]

cuda_compiler_version:         # [win or linux]
  - none                       # [win or linux]
  - 12.8                       # [win or linux]
  - 13.0                       # [win or linux]
  - 13.1                       # [win or linux]

zip_keys:                      # [win or linux]
  -                            # [win or linux]
    - gpu_variant              # [win or linux]
    - cuda_compiler_version    # [win or linux]
